### ISSUE TITLE
eu-central-1 - version: 6/7

### ISSUE THREAD

**Issue by pavelloz** [shelfio/chrome-aws-lambda-layer#6]
Hello,

While i was verifying if the layer does work i think i found out that version 6 and 7 are missing from `eu-central-1` region. 5 is the last version available.

> arn:aws:lambda:eu-central-1:764866452798:layer:chrome-aws-lambda:5

I guess some publishing script missed this (maybe not only this) region.

**Comment by andreme** [comment]
Versions 6 and 7 are missing for ap-southeast-2 too. (Or they are not made public)

**Comment by vladgolubev** [comment]
Hey @andreme @pavelloz 

Version 6 & 7 are missing in all regions other than `us-east-1` because they were added relatively recently. So the first two publications were only in `us-east-1`.

AWS increments layer version automatically, so I can't align layer version to be the same across all regions.

I've just added full ARNs of all layer versions in all regions: https://github.com/shelfio/chrome-aws-lambda-layer#available-regions
